### ISSUE TITLE
log messeges of `sb-ovsdb` contain unreasonable amount of timed out errors

### ISSUE THREAD

**Issue by OmerBenHayun** [IBM/ovsdb-etcd#229] opened 2021-06-15 12:39 UTC
```
[2:37 PM] omer@omer-VirtualBox:~/work/src/github.com/ovn-org/ovn-kubernetes$ kn logs ovnkube-db-8684c68bf8-qxf2w sb-ovsdb | head -n 50
================== ovnkube.sh --- version: 3 ================
 ==================== command: sb-ovsdb-etcd
 =================== hostname: ovn-control-plane
 =================== daemonset version 3
=============== run-sb-ovsdb-etcd (wait for etcd_ready)
info: Waiting for etcd_ready to come up, waiting 1s ...
info: Waiting for etcd_ready to come up, waiting 5s ...
etcd_ready came up in 2 5 sec tries
================= start sb-ovsdb-etcd server ============================ 
======= checking [172.18.0.2]:6641 OVSDB instance ===============
ovsdb-client  list-dbs tcp:[172.18.0.2]:6641
=============== setting ovnkube-db endpoints to 172.18.0.2
endpoints/ovnkube-db created
E0615 11:27:11.250435      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57280 : client connection is closed
E0615 11:27:11.250462      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57280 : client connection is closed
E0615 11:27:11.264555      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57282 : client connection is closed
E0615 11:27:11.264780      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57282 : client connection is closed
E0615 11:27:11.295009      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57284 : client connection is closed
E0615 11:27:11.295083      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57284 : client connection is closed
E0615 11:27:11.589328      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57286 : client connection is closed
E0615 11:27:11.589351      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57286 : client connection is closed
E0615 11:27:11.612248      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57290 : client connection is closed
E0615 11:27:11.612375      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57290 : client connection is closed
E0615 11:27:11.663539      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57292 : client connection is closed
E0615 11:27:11.663618      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57292 : client connection is closed
E0615 11:27:11.745806      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57294 : client connection is closed
E0615 11:27:11.745988      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57294 : client connection is closed
E0615 11:27:12.645174      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.3:46144 : client connection is closed
E0615 11:27:12.645226      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.3:46144 : client connection is closed
E0615 11:27:12.815332      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.4:34598 : client connection is closed
E0615 11:27:12.815532      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.4:34598 : client connection is closed
E0615 11:27:12.819208      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57312 : client connection is closed
E0615 11:27:12.821160      16 handler.go:351]  error monitorCanceledNotification to 172.18.0.2:57312 : client connection is closed
E0615 11:27:16.380347      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="21" "txnid"="ZWaTvYoRPSLSrBUerkDVxg" 
E0615 11:27:16.396992      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="22" "txnid"="8zQMcUCeuJGWVboRvZQL4f" 
E0615 11:27:16.400667      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="23" "txnid"="JhGbM4XL3E9tSEGJ5FBdiV" 
E0615 11:27:16.404760      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="24" "txnid"="A5imxnhjXCfixjHzQZJAT6" 
E0615 11:27:16.408819      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="25" "txnid"="wVjQVQi2GZwgyGZhprThbB" 
E0615 11:27:16.412467      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="26" "txnid"="9nqvLnMhyFs7g6ycqEVQUH" 
E0615 11:27:16.416539      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="27" "txnid"="qqFwqzbKfqWnV6aMMr7xfd" 
E0615 11:27:16.421980      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="28" "txnid"="MJ3rv7Hup2do4V7iZhHTi7" 
E0615 11:27:16.426348      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="29" "txnid"="VnmjuKDLLFgFB55RY5fgUn" 
E0615 11:27:16.431943      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="30" "txnid"="DquQry7JuBJRMWfWFDXvag" 
E0615 11:27:16.445652      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="31" "txnid"="sBhmFB8ZecTPCRDuRoRz6F" 
E0615 11:27:16.450334      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="32" "txnid"="yHt6ydX2zAoZ9EoV4WHiWK" 
E0615 11:27:16.455914      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="33" "txnid"="mGPgEna9JeMLyzaaVtSdoR" 
E0615 11:27:16.460293      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="34" "txnid"="RZpDYZzcFiC2tBjcrCfBHo" 
E0615 11:27:16.464735      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="35" "txnid"="xRNJBov9gKmgwjakWL7mVg" 
E0615 11:27:16.469210      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="36" "txnid"="9m3opPLhne8fTY4Yjued4n" 
E0615 11:27:16.478926      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="37" "txnid"="dupm9B5LYWjgTgeQeWuPeR" 
```

there are many errors of the form :
```
E0615 11:27:16.478926      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="37" "txnid"="dupm9B5LYWjgTgeQeWuPeR" 
```

we can take the first error (`"txnid"="ZWaTvYoRPSLSrBUerkDVxg" `) and look on it's context:
```
[root@ovn-control-plane ovn]# cat sb-ovsdb-etcd.log | grep dupm9B5LYWjgTgeQeWuPeR
I0615 11:27:16.472101      16 transact.go:556]  "msg"="new transaction" "address"="172.18.0.4:34536" "id"="37" "txnid"="dupm9B5LYWjgTgeQeWuPeR" "request"={"dbname":"OVN_Southbound","operations":[{"op":"wait","table":"Chassis","rows":[{"other_config":["map",[["datapath-type",""],["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],["is-interconn","false"],["ovn-bridge-mappings",""],["ovn-chassis-mac-mappings",""],["ovn-cms-options",""],["ovn-enable-lflow-cache","true"],["ovn-limit-lflow-cache",""],["ovn-memlimit-lflow-cache-kb",""],["ovn-monitor-all","true"],["port-up-notif","true"]]]}],"columns":["other_config"],"timeout":0,"where":[["_uuid","==",["uuid","0626c324-9dde-4285-b141-f498611e60f6"]]],"until":"=="},{"op":"update","table":"Chassis","row":{"external_ids":["map",[["datapath-type",""],["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],["is-interconn","false"],["ovn-bridge-mappings","physnet:breth0,locnet:br-local"],["ovn-chassis-mac-mappings",""],["ovn-cms-options",""],["ovn-enable-lflow-cache","true"],["ovn-limit-lflow-cache",""],["ovn-memlimit-lflow-cache-kb",""],["ovn-monitor-all","true"],["port-up-notif","true"]]],"other_config":["map",[["datapath-type",""],["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],["is-interconn","false"],["ovn-bridge-mappings","physnet:breth0,locnet:br-local"],["ovn-chassis-mac-mappings",""],["ovn-cms-options",""],["ovn-enable-lflow-cache","true"],["ovn-limit-lflow-cache",""],["ovn-memlimit-lflow-cache-kb",""],["ovn-monitor-all","true"],["port-up-notif","true"]]]},"where":[["_uuid","==",["uuid","0626c324-9dde-4285-b141-f498611e60f6"]]]},{"op":"comment","comment":"ovn-controller\novn-controller: updating chassis 'be725e94-1ed9-45c0-8ed7-370b0546aec0'"}]} "size"=3
I0615 11:27:16.472937      16 transact.go:234]  "msg"="etcd transaction" "address"="172.18.0.4:34536" "id"="37" "txnid"="dupm9B5LYWjgTgeQeWuPeR" "etcd"="#then 2, #events 0, #events-nil 0"
I0615 11:27:16.473122      16 transact.go:240]  "msg"="etcd processing" "address"="172.18.0.4:34536" "id"="37" "txnid"="dupm9B5LYWjgTgeQeWuPeR" "child"="#then 2, #events 0, #events-nil 0" "index"=0
I0615 11:27:16.478838      16 transact.go:1918]  "msg"="checking row equal" "address"="172.18.0.4:34536" "id"="37" "row"={"_uuid":["uuid","0626c324-9dde-4285-b141-f498611e60f6"],"encaps":["uuid","9f658dce-060d-405f-881d-0ef1bad0bd50"],"external_ids":["map",[["ovn-memlimit-lflow-cache-kb",""],["is-interconn","false"],["ovn-bridge-mappings","physnet:breth0"],["ovn-limit-lflow-cache",""],["ovn-enable-lflow-cache","true"],["ovn-cms-options",""],["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],["datapath-type",""],["ovn-monitor-all","true"],["port-up-notif","true"],["ovn-chassis-mac-mappings",""]]],"hostname":"ovn-worker","name":"be725e94-1ed9-45c0-8ed7-370b0546aec0","nb_cfg":0,"other_config":["map",[["ovn-bridge-mappings","physnet:breth0"],["ovn-enable-lflow-cache","true"],["ovn-limit-lflow-cache",""],["ovn-memlimit-lflow-cache-kb",""],["port-up-notif","true"],["is-interconn","false"],["ovn-cms-options",""],["ovn-monitor-all","true"],["datapath-type",""],["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],["ovn-chassis-mac-mappings",""]]],"transport_zones":["set",[]],"vtep_logical_switches":["set",[]]} "txnid"="dupm9B5LYWjgTgeQeWuPeR" "expected"={"other_config":["map",[["datapath-type",""],["ovn-chassis-mac-mappings",""],["ovn-monitor-all","true"],["ovn-enable-lflow-cache","true"],["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],["port-up-notif","true"],["ovn-memlimit-lflow-cache-kb",""],["ovn-bridge-mappings",""],["is-interconn","false"],["ovn-limit-lflow-cache",""],["ovn-cms-options",""]]]} "result"=false
E0615 11:27:16.478926      16 transact.go:1939]  "msg"="timed out" "error"="timed out" "address"="172.18.0.4:34536" "id"="37" "txnid"="dupm9B5LYWjgTgeQeWuPeR" 
```

**Comment by hunchback** [comment] 2021-06-15 13:34
the problem is column `other_config` and the map key `ovn-bridge-mappings`
- actual value: "physnet:breth0"
- expected value: ""

```
# row
{
"other_config":["map",[
["ovn-bridge-mappings","physnet:breth0"],
["ovn-enable-lflow-cache","true"],
["ovn-limit-lflow-cache",""],
["ovn-memlimit-lflow-cache-kb",""],
["port-up-notif","true"],
["is-interconn","false"],
["ovn-cms-options",""],
["ovn-monitor-all","true"],
["datapath-type",""],
["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],
["ovn-chassis-mac-mappings",""]]],
}

# expected
{
"other_config":["map",[
+ ["datapath-type",""],
+ ["ovn-chassis-mac-mappings",""],
+ ["ovn-monitor-all","true"],
+ ["ovn-enable-lflow-cache","true"],
+ ["iface-types","bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan"],
+ ["port-up-notif","true"],
+ ["ovn-memlimit-lflow-cache-kb",""],
- ["ovn-bridge-mappings",""],
+ ["is-interconn","false"],
+["ovn-limit-lflow-cache",""],
+ ["ovn-cms-options",""]]]
}"
```

**Comment by roytman** [comment] 2021-06-24 03:22
Resolved with fixing  `modified` notifications for Maps and  Sets

**Closed by roytman** 2021-06-24 03:22 UTC
